/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NovoPedidoRouteImport } from './routes/novo-pedido'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as TecnicosRouteImport } from './routes/tecnicos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoPedidoRoute = NovoPedidoRouteImport.update({
  id: '/novo-pedido',
  path: '/novo-pedido',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicosRoute = TecnicosRouteImport.update({
  id: '/tecnicos',
  path: '/tecnicos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/novo-pedido': typeof NovoPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/novo-pedido': typeof NovoPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/clientes': typeof ClientesRoute
  '/login': typeof LoginRoute
  '/novo-pedido': typeof NovoPedidoRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
  '/tecnicos': typeof TecnicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/clientes'
    | '/login'
    | '/novo-pedido'
    | '/pedidos'
    | '/produtos'
    | '/tecnicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/clientes'
    | '/login'
    | '/novo-pedido'
    | '/pedidos'
    | '/produtos'
    | '/tecnicos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/clientes'
    | '/login'
    | '/novo-pedido'
    | '/pedidos'
    | '/produtos'
    | '/tecnicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ClientesRoute: typeof ClientesRoute
  LoginRoute: typeof LoginRoute
  NovoPedidoRoute: typeof NovoPedidoRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
  TecnicosRoute: typeof TecnicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-pedido': {
      id: '/novo-pedido'
      path: '/novo-pedido'
      fullPath: '/novo-pedido'
      preLoaderRoute: typeof NovoPedidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnicos': {
      id: '/tecnicos'
      path: '/tecnicos'
      fullPath: '/tecnicos'
      preLoaderRoute: typeof TecnicosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ClientesRoute: ClientesRoute,
  LoginRoute: LoginRoute,
  NovoPedidoRoute: NovoPedidoRoute,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
  TecnicosRoute: TecnicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
